### ISSUE TITLE
Add a light showing the status of pktwallet backend

### ISSUE THREAD

**Issue by cjdelisle** [artrepreneur/PKT-Cash-Wallet#11]
The idea would be to add a little "LED" like lightbulb to the UI which shows:
* red if there's a problem launching pktwallet (ideally with a small explanation on mouseover) 
* yellow if pktwallet is currently syncing
* green if pktwallet seems to be synced

`btcctl --wallet getinfo` should indicate whether the wallet seems to be syncing.

**Comment by artrepreneur** [comment]
Completed, and closing.
