### ISSUE TITLE
Avoid killing pktwallet if it was started by the user manually

### ISSUE THREAD

**Issue by cjdelisle** [artrepreneur/PKT-Cash-Wallet#13]
As part of being a good neighbor to the other applications running on the machine, it would be good not to kill an existing pktwallet if it is running, instead the better thing to do is raise a dialog telling the user that pktwallet is already running and they should stop it from the command line before launching the app.

A couple of additional nice-to-haves would be:
1. If `btcctl --wallet getinfo` works then attempt to simply connect to the existing wallet. If there is a major version difference then `btcctl` will refuse to talk to the wallet so it won't.
2. If the wallet that is running happens to be the one which was started by PKTWallet.app, then it would be a good idea shut it down and restart it because it is not something the user started.

**Comment by artrepreneur** [comment]
Completed.
