### ISSUE TITLE
When launching the wallet, it crashes with a stack trace

### ISSUE THREAD

**Issue by cjdelisle** [artrepreneur/PKT-Cash-Wallet#14]
I'm getting this in my logs:

```
2020-06-18 10:23:34.164 [INF] BTCD btcd.go:66: Version 1.1.0-beta+f9cc9937

2020-06-18 10:23:34.164 [INF] BTCD btcd.go:275: Loading block database from '/Users/user/Library/Application Support/Pktd/data/pkt/blocks_ffldb'

Traceback (most recent call last):
  File "PKTWallet.py", line 2198, in <module>
  File "PKTWallet.py", line 1957, in status_light
  File "PKTWallet.py", line 43, in pktwllt_synching
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cjdelisle** [comment]
If I had to take a guess as to what's happening, I would say that [get_inf()](https://github.com/artrepreneur/PKT-Cash-Wallet/blob/5366056eb73df37bac7579770978826a41b7d893/wlltinf.py#L16) is throwing but the error doesn't propagate because of the `try/except:pass` which causes it to implicitly return None

**Comment by artrepreneur** [comment]
It's a little difficult to reproduce, but if get_inf() is returning NoneType then chances are that the wallet daemon isn't alive. I will produce a solution to this bug, albeit somewhat blindly, but I'm not sure why the wallet seems to have died.

**Comment by cjdelisle** [comment]
AFAICT there's no way out of that function except to return something meaningful or raise an error, so if it raises an error, one solution is to return {}, which for the purpose of the indicator light seems like a good approach to me.

**Comment by artrepreneur** [comment]
Thanks. Yeah, like I said, I can produce the solution, and I already have. I just don't know what the exception from the wallet was and it's impossible to reproduce on my end, but I will make it verbose so you can track it. I'll publish as soon as I deal with one other issue.

**Comment by artrepreneur** [comment]
Published the fix
