### ISSUE TITLE
Zulu is telling me the wallet password is incorrect

### ISSUE THREAD

**Issue by rsalmei** [artrepreneur/PKT-Cash-Wallet#29]
Hello,

Please, could you help me?
I created the wallet last month, I'm pretty sure I have the correct password recorded, as well as the seed words, but it keeps telling me it is wrong.

I've created a very strong password, with a length of 64 chars, and including symbols like `@#%^&*`.
Is there any problem with these?

How could I retrieve the funds in there?
I've tried in another computer to recreate the wallet with the same seed and pass, but in spite of Zulu not giving me any error, my addresses and funds did not appear.

Can someone help? Thanks.

**Comment by bannor11** [comment]
> Hello,
> 
> Please, could you help me? I created the wallet last month, I'm pretty sure I have the correct password recorded, as well as the seed words, but it keeps telling me it is wrong.
> 
> I've created a very strong password, with a length of 64 chars, and including symbols like `@#%^&*`. Is there any problem with these?
> 
> How could I retrieve the funds in there? I've tried in another computer to recreate the wallet with the same seed and pass, but in spite of Zulu not giving me any error, my addresses and funds did not appear.
> 
> Can someone help? Thanks.

I had the same issue.  I believe it's due to the symbols in your password.  You need to recreate the wallet using the same seed and a different password without special characters.  Give time for your wallet to sync, but your funds should re-appear once it's sync'd.

**Comment by rsalmei** [comment]
It worked! Thank you @bannor11!
