### ISSUE TITLE
Avoid using kill-9 to stop pktd/pktwallet

### ISSUE THREAD

**Issue by cjdelisle** [artrepreneur/PKT-Cash-Wallet#8]
kill-9 runs the risk of databases not being shut down cleanly and ending up corrupted - so the better thing to do is use a SIGINT and then wait for the process to shut down. In practice it should stop within a couple of seconds, but the thing to do is check if it's stopped once per second until 30 seconds and then issue a kill-9.

**Comment by artrepreneur** [comment]
Completed.
