### ISSUE TITLE
Not working correctly when there is no existing wallet

### ISSUE THREAD

**Issue by cjdelisle** [artrepreneur/PKT-Cash-Wallet#9]
To reproduce:
* `mv ~/Library/Application\ Support/Pktwallet/ ~/Library/Application\ Support/_Pktwallet/`
* Launch the pktwallet
* Observe that it doesn't prompt you to create a wallet and instead it thinks a wallet exists

**Comment by artrepreneur** [comment]
Seems to be fixed now.
